name: Deploy-StageğŸ”µ

on:
  push:
    branches:
      - stage
jobs:
  build:
    name: ğŸš€ Deploy to Staging
    runs-on: ubuntu-latest
    steps:

      - name: âœ… Checkout
        uses: actions/checkout@v2

      - name: âŒ›Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: â• Install Deps
        run: python -m pip install --upgrade build twine pytest

      - name: ğŸ§ª Test
        run : python -m pytest -rx

      - name: âš™ï¸ Build
        run: python -m build


      - name: ğŸš€ Publish to PyPI
        run: python -m twine upload -r testpypi dist/* -u __token__ -p ${{secrets.PYPI_TEST_API_TOKEN}} --verbose             